name: quiez_clarissa_labpm3
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather_24pt-Regular.ttf
        - asset: assets/fonts/Merriweather_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Merriweather_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Merriweather_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Merriweather_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Merriweather_24pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Merriweather_24pt-LightItalic.ttf
          weight: 300
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800

